### ISSUE TITLE
rpm packages contain deb inside

### ISSUE THREAD

**Issue by sashaCher** [conjurinc/debify#57]
It looks like fpm packaging is working as snowball.
Firstly it creates deb package file and then when it creates rpm it packs previously created deb in.
I can see it in evoke rpm for example.

**Comment by sashaCher** [comment]
The concrete bug can be a symptom of may be worse problem when each repo is packing the whole repo content + any temporary files that exists in the repo at the packing type.
There is a risk to pack sensitive internal information into installation package.

**Comment by eladkug** [comment]
Duplicate to ONYX-10847
